// <auto-generated />
using BUSAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BUSAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240428201638_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BUSAPI.Models.Onibus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Linha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeLinha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("PontoFinal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("PontoPartida")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int>("TempoEspera")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_ONIBUS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Linha = "1234A",
                            NomeLinha = "Parque Luiz Fernando",
                            PontoFinal = "Av. Vitor Luz",
                            PontoPartida = "Parque Luiz Cardoso",
                            Situacao = 1,
                            TempoEspera = 5
                        },
                        new
                        {
                            Id = 2,
                            Linha = "1345A",
                            NomeLinha = "Av. Professora Quitereia",
                            PontoFinal = "R. Sarjento Bruno",
                            PontoPartida = "Av. Professora Quiteria",
                            Situacao = 1,
                            TempoEspera = 15
                        },
                        new
                        {
                            Id = 3,
                            Linha = "1456A",
                            NomeLinha = "Vila Guilherme",
                            PontoFinal = "Rua Soldado   Brad kynndy",
                            PontoPartida = "Vila Guilherme",
                            Situacao = 1,
                            TempoEspera = 25
                        },
                        new
                        {
                            Id = 4,
                            Linha = "1567A",
                            NomeLinha = "AV. Marion",
                            PontoFinal = "Rua Professora Fatima",
                            PontoPartida = "Av. Marion",
                            Situacao = 1,
                            TempoEspera = 35
                        },
                        new
                        {
                            Id = 5,
                            Linha = "1678A",
                            NomeLinha = "Av. Eduardo Kaue",
                            PontoFinal = " Rua Senior Bruno Leitao",
                            PontoPartida = "Av. Eduardo Kaue",
                            Situacao = 3,
                            TempoEspera = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
